// ============================================================
//  uart_loopback_tb.v -- Comprehensive Self-Checking UART TX/RX Loopback Test
//
//  Directly loops CPU TX pin into CPU RX pin.
//  Verifies that serial frames generated by CPU execution ('H', 'i')
//  are received back on top-level uart_rx_ready and uart_rx_data.
// ============================================================
`timescale 1ns/1ps

module uart_loopback_tb;

    integer pass_count  = 0;
    integer fail_count  = 0;
    integer total_tests = 0;

    localparam SIM_CLK_FREQ  = 200_000;
    localparam SIM_BAUD_RATE = 10_000;
    localparam CLK_HALF      = 2500; // 200 kHz
    localparam BIT_PERIOD    = (1_000_000_000 / SIM_BAUD_RATE); // 100,000 ns

    reg  clk, reset;
    wire tx_out;
    wire rx_in = tx_out; // TX looped back directly to RX
    wire uart_rx_ready;
    wire [7:0] uart_rx_data;
    wire [31:0] pc, inst, alu_result, wd, rd;
    wire result_src, memwrite, alu_src, regwrite, pc_src;
    wire [1:0] imm_src;

    task check_byte(input string name, input [7:0] actual, input [7:0] expected);
        total_tests = total_tests + 1;
        if (actual === expected) begin
            pass_count = pass_count + 1;
            $display("[PASS] [%0t] %s: 0x%02X ('%c')", $time, name, actual, actual);
        end else begin
            fail_count = fail_count + 1;
            $display("[FAIL] [%0t] %s: Expected = 0x%02X ('%c'), Actual = 0x%02X ('%c')",
                     $time, name, expected, expected, actual, actual);
        end
    endtask

    risc_v #(
        .CLK_FREQ  (SIM_CLK_FREQ),
        .BAUD_RATE (SIM_BAUD_RATE)
    ) DUT (
        .clk          (clk),
        .reset        (reset),
        .tx           (tx_out),
        .rx           (rx_in),
        .uart_rx_ready(uart_rx_ready),
        .uart_rx_data (uart_rx_data),
        .result_src   (result_src),
        .memwrite     (memwrite),
        .alu_src      (alu_src),
        .regwrite     (regwrite),
        .pc_src       (pc_src),
        .imm_src      (imm_src),
        .pc           (pc),
        .inst         (inst),
        .alu_result   (alu_result),
        .wd           (wd),
        .rd           (rd)
    );

    initial clk = 0;
    always #CLK_HALF clk = ~clk;

    // Expected characters
    reg [7:0] expected_stream [0:3];
    initial begin
        expected_stream[0] = "H";
        expected_stream[1] = "i";
        expected_stream[2] = "H";
        expected_stream[3] = "i";
    end

    integer rx_count;

    initial begin
        $display("\n==================================================");
        $display("STARTING DIRECT UART TX->RX LOOPBACK TEST");
        $display("==================================================\n");

        reset = 1;
        rx_count = 0;

        repeat (10) @(posedge clk);
        @(negedge clk);
        reset = 0;
        $display("[INFO] [%0t] Reset released, loopback active...", $time);

        while (rx_count < 4) begin
            @(posedge uart_rx_ready);
            check_byte($sformatf("Loopback Received Character #%0d", rx_count + 1),
                       uart_rx_data, expected_stream[rx_count]);
            rx_count = rx_count + 1;
        end

        #20000;
        $display("\n=================================");
        $display("SIMULATION SUMMARY: Loopback Test");
        $display("Total Tests: %0d", total_tests);
        $display("Passed:      %0d", pass_count);
        $display("Failed:      %0d", fail_count);
        $display("=================================\n");

        if (fail_count == 0 && total_tests > 0)
            $display("[RESULT] ALL TESTS PASSED");
        else
            $display("[RESULT] SIMULATION FAILED");

        $finish;
    end

    // Watchdog
    initial begin
        #100_000_000;
        $display("[ERROR] [%0t] Simulation watchdog timeout reached!", $time);
        $finish;
    end

endmodule

